# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimate the Weights that Maximize the Probability of Observed Outcomes
#'
#' With initial parameters, this function iteratively calculates the weights that seek to maximize the probability that an outcome t is best predicted by a series of forecast models. The function stops at iteration j and return the final weights when the estimated probability at iteration j converges based on a pre-defined threshold of your choosing.
#' 
#' @param y A numeric vector that indicates observed election outcomes.
#' @param ftk A numeric vector that indicates the mean of the forecast models. The models are assumed to follow a normal distribution.
#' @param weights A numeric vector that indicates the initial weights assigned to the forecast models.
#' @param sd A value that indicates the standard deviation of the forecast models. In this function, it is assumed to be 1 and remains consistent across the models.
#' @param threshold A value that indicates the level of tolerance in the difference between the estimated probability at iteration j-1 the estimated probability at iteration j.
#' @return A list with three elements:
#'  \item{final_weights}{The final weights that maximize the probability that an outcome t is best predicted by a series of forcast models, given a pre-defined tolerance threshold.}
#'  \item{final_density}{The final maximized probability.}
#'  \item{iterations}{The number of iterations the function goes through to reach the maximized probability.}
#' @author Rex W. Deng <\email{weiye.deng@@wustl.edu}>
#' @note The value in Equation (1) is what this function seeks to maximize.
#' @note The function uses the \code{est_ztk()} function (see Equation 2) and the \code{update_weights()} function (see Equation 3) to iteratively update the weights. 
#' @examples
#' y <- c(0.1,0.2,0.5)
#' ftk <- seq(0,1,0.1)
#' sd <- 1
#' weights <- rep(1/length(ftk), length(ftk)) ## Intially assign equal weight to each model
#' est_finalWeights(y=y, ftk=ftk, weights=weights, sd=1, threshold=0.0001)
#'
#' @seealso \code{get_num_den}, \code{update_weights}, \code{est_finalweights}
#'
#' @rdname est_finalWeights
#'
#' @export
est_finalWeights <- function(y, ftk, sd, weights, threshold) {
    .Call('_EMBARcpp_est_finalWeights', PACKAGE = 'EMBARcpp', y, ftk, sd, weights, threshold)
}

#' Calculate the Latent Quantity ztk
#'
#' Calculate the Latent Quantity ztk, which is the fraction between the weighted density for each observed outcome t and the sum of weighted density across k forecast models for each t.
#' 
#' @param y A numeric vector that indicates observed election outcomes.
#' @param ftk A numeric vector that indicates the mean of the forecast models. The models are assumed to follow a normal distribution.
#' @param weights A numeric vector that indicates the initial weights assigned to the forecast models.
#' @param sd A value that indicates the standard deviation of the forecast models. In this function, it is assumed to be 1 and remains consistent across the models.
#' @return A matrix, with the entry (t, k) representing the probability that observation t was best predicted by model k.
#' @author Rex W. Deng <\email{weiye.deng@@wustl.edu}>
#' @note Refer to the equation in Step 2.
#' @examples
#' y <- c(0.1,0.2,0.5)
#' ftk <- seq(0,1,0.1)
#' sd <- 1
#' weights <- rep(1/length(ftk), length(ftk)) ## Intially assign equal weight to each model
#' est_ztk(y=y, ftk=ftk, weights=weights, sd=1)
#'
#' @seealso \code{get_num_den}, \code{update_weights}, \code{est_finalweights}
#'
#' @rdname est_ztk
#'
#' @export
est_ztk <- function(y, ftk, sd, weights) {
    .Call('_EMBARcpp_est_ztk', PACKAGE = 'EMBARcpp', y, ftk, sd, weights)
}

#' Calculate the Weighted Density for Observed Outcomes and the Sum of Weighed Density for Each Model
#'
#' Calculate the weighted density for each observed outcome t and the sum of weighted density across k forecast models for each t.
#' 
#' @param y A numeric vector that indicates observed election outcomes.
#' @param ftk A numeric vector that indicates the mean of the forecast models. The models are assumed to follow a normal distribution.
#' @param weights A numeric vector that indicates the initial weights assigned to the forecast models.
#' @param sd A value that indicates the standard deviation of the forecast models. In this function, it is assumed to be 1 and remains consistent across the models.
#' @return A list with two elements:
#'  \item{numerator_matrix}{Each entry (t, k) documents the weighted probability of each election outcome t in each forcast model k.}
#'  \item{denominator_vector}{The sum of weighted density across k forecast models for each t.}
#' @author Rex W. Deng <\email{weiye.deng@@wustl.edu}>
#' @note Refer to the equation in Equation (2). The numerator matrix refers to the values in the numerator and the denominator vectore refers to the values in the deminator.
#' @note This is an intermediate function, which is mainly used to calculate the ztk matrix in Equation (2). See how to calculate the ztk matrix by referring to the function \code{est_zsk()}.
#' @examples
#' y <- c(0.1,0.2,0.5)
#' ftk <- seq(0,1,0.1)
#' sd <- 1
#' weights <- rep(1/length(ftk), length(ftk)) ## Intially assign equal weight to each model
#' get_num_den(y=y, ftk=ftk, weights=weights, sd=1)
#'
#' @seealso \code{est_ztk}, \code{update_weights}, \code{est_finalweights}
#' @rdname get_num_den
#'
#' @export
get_num_den <- function(y, ftk, sd, weights) {
    .Call('_EMBARcpp_get_num_den', PACKAGE = 'EMBARcpp', y, ftk, sd, weights)
}

#' Update Weights with a ztk Matrix
#'
#' Update weights with a ztk matrix by estimating the expected value of the weights across observed outcomes t.
#' 
#' @param ztk_mat A ztk matrix output from the function \code{est_ztk{}}, with the entry (t, k) representing the probability that observation t was best predicted by model k.
#' @return A vector that provides the new weights for each model k.
#' @author Rex W. Deng <\email{weiye.deng@@wustl.edu}>
#' @note Refer to the equation in Step 3.
#' @examples
#' library(EMBARcpp)
#' y <- c(0.1,0.2,0.5)
#' ftk <- seq(0,1,0.1)
#' sd <- 1
#' weights <- rep(1/length(ftk), length(ftk)) ## Intially assign equal weight to each model
#' ## Make sure `est_ztk()` is available in the global envrionment; NOT RUN
#' ## update_weights(esk_ztk(y=y, ftk=ftk, weights=weights, sd=1))
#'
#' @seealso \code{get_num_den}, \code{est_ztk}, \code{est_finalweights}
#' @rdname update_weights
#'
#' @export
update_weights <- function(ztk_mat) {
    .Call('_EMBARcpp_update_weights', PACKAGE = 'EMBARcpp', ztk_mat)
}

